# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8369171016c1b0c101057ded2f28cf7c9df918fba9832154fcf1b20caf49def144a38f109fef4f204df3dc1cb440e5beeb6aa97a2b192535b8d73eba0930ea46

test:
  secret_key_base: 592ad4cdf3bc4b18fcc2a933f9b231101fb88b54fc8bcecd0f9987f9ec5f720f60afd3290deaacbd656f74b771a3ec7a57649d8a6015ac4a475a5bbdf46bbcfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
